[package]
name = "antigravity-ide"
description = "Antigravity IDE - Build the new way"
cli_name = "antigravity-ide"

[version]
local_strategy = "file"
url = "https://antigravity.google/download"
search_linked_js = true
remote_pattern = 'stable/(\d+\.\d+\.\d+-\d+)/linux-x64/Antigravity%20IDE\.tar\.gz'
local_file = "resources/app/product.json"
local_pattern = '"ideVersion":\s*"([^"]+)"'
match_pattern = '^(\d+\.\d+\.\d+)'

[download]
url = "https://edgedl.me.gvt1.com/edgedl/release2/j0qc3/antigravity/stable/{version}/linux-x64/Antigravity%20IDE.tar.gz"
format = "tar.gz"

[install]
strip_components = 1
executable_path = "antigravity-ide"

[integration]
generate = true
icon = "antigravity-ide.png"

[integration.desktop]
Name = "Antigravity IDE"
Comment = "Antigravity IDE - Build the new way"
Terminal = false
Categories = "Development;IDE;"
MimeType = "x-scheme-handler/antigravity-ide;"
StartupNotify = true
